# Generated by Django 5.1.4 on 2025-01-26 22:21

from django.db import migrations

def add_coaches(apps, schema_editor):
    user1 = User.objects.create_user(
        username="john_doe",
        first_name="John",
        last_name="Doe",
        email="john.doe@example.com",
        password="password123",
        is_coach=True,
        gender="M"
    )

    user2 = User.objects.create_user(
        username="jane_smith",
        first_name="Jane",
        last_name="Smith",
        email="jane.smith@example.com",
        password="password123",
        is_coach=True,
        gender="F"
    )

    user3 = User.objects.create_user(
        username="mark_brown",
        first_name="Mark",
        last_name="Brown",
        email="mark.brown@example.com",
        password="password123",
        is_coach=True,
        gender="M"
    )

    # Tworzenie coachów (Coach)
    coach1 = Coach.objects.create(
        user=user1,
        hourly_rate=50.0,
        description="Experienced fitness coach specializing in strength training.",
        phone_number=123456789
    )

    coach2 = Coach.objects.create(
        user=user2,
        hourly_rate=65.0,
        description="Certified yoga instructor with a focus on mindfulness and flexibility.",
        phone_number=987654321
    )

    coach3 = Coach.objects.create(
        user=user3,
        hourly_rate=40.0,
        description="Enthusiastic personal trainer for beginners and advanced athletes.",
        phone_number=555123456
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_client_membership_remove_payment_client_and_more'),
    ]

    operations = [
    ]
