# Generated by Django 4.2.18 on 2025-01-26 18:17

from django.db import migrations

def add_memberships(apps, schema_editor):
    Membership = apps.get_model('memberships', 'Membership')
    memberships = [Membership(name='basic', price_1=150, price_6=150, price_12=100),
                   Membership(name='student', price_1=130, price_6=99.99, price_12=85),
                   Membership(name='premium', price_1=180, price_6=150, price_12=125),]
    for membership in memberships:
        membership.save()

class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_memberships),
    ]
