# Generated by Django 5.1.4 on 2025-01-26 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='max_participans',
            new_name='max_participants',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='clients',
        ),
        migrations.AddField(
            model_name='workout',
            name='client',
            field=models.ManyToManyField(related_name='client_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='WorkoutParticipation',
        ),
    ]
